FROM podman2vm-arch-base:latest
COPY containers/LXD-openwrt/openwrt.yml /config/lxd/profiles/
    #lxd init --minimal && \
    #lxc storage create default dir && \
    #lxc init --profile default --profile openwrt --storage default openwrt openwrt && \
RUN lxd --group=lxd & \
    lxd waitready --timeout=600 && \
    lxc image import /output/openwrt.tar --alias openwrt && \
    lxd shutdown
    #lxc profile create openwrt && \
    #lxc profile edit openwrt < /config/lxd/profiles/openwrt.yml && \
RUN systemctl enable container@openwrt.service