### This is a YAML representation of the profile.
### Any line starting with a '# will be ignored.
###
### A profile consists of a set of configuration items followed by a set of
### devices.
###
### An example would look like:
### name: onenic
### config:
###   raw.lxc: lxc.aa_profile=unconfined
### devices:
###   eth0:
###     nictype: bridged
###     parent: lxdbr0
###     type: nic
###
### Note that the name is shown but cannot be changed

config:
  raw.lxc: |
    lxc.cgroup2.devices.allow = a
    lxc.cgroup.devices.allow = a
    lxc.autodev = 1
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  dev:
    path: /dev
    source: /dev
    type: disk
    shift: true
  proc:
    path: /proc
    source: /proc
    type: disk
    shift: true
  sys:
    path: /sys
    source: /sys
    type: disk
    shift: true
name: privileged
used_by: []